#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBHELPDESK01")]
	public partial class DCExamenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBL_DEPARTAMENTO(TBL_DEPARTAMENTO instance);
    partial void UpdateTBL_DEPARTAMENTO(TBL_DEPARTAMENTO instance);
    partial void DeleteTBL_DEPARTAMENTO(TBL_DEPARTAMENTO instance);
    partial void InsertTBL_ESTADO(TBL_ESTADO instance);
    partial void UpdateTBL_ESTADO(TBL_ESTADO instance);
    partial void DeleteTBL_ESTADO(TBL_ESTADO instance);
    partial void InsertTBL_INCIDENTE(TBL_INCIDENTE instance);
    partial void UpdateTBL_INCIDENTE(TBL_INCIDENTE instance);
    partial void DeleteTBL_INCIDENTE(TBL_INCIDENTE instance);
    partial void InsertTBL_OBSERVACION(TBL_OBSERVACION instance);
    partial void UpdateTBL_OBSERVACION(TBL_OBSERVACION instance);
    partial void DeleteTBL_OBSERVACION(TBL_OBSERVACION instance);
    partial void InsertTBL_PERSONA(TBL_PERSONA instance);
    partial void UpdateTBL_PERSONA(TBL_PERSONA instance);
    partial void DeleteTBL_PERSONA(TBL_PERSONA instance);
    partial void InsertTBL_PRIORIDAD(TBL_PRIORIDAD instance);
    partial void UpdateTBL_PRIORIDAD(TBL_PRIORIDAD instance);
    partial void DeleteTBL_PRIORIDAD(TBL_PRIORIDAD instance);
    partial void InsertTBL_ROL(TBL_ROL instance);
    partial void UpdateTBL_ROL(TBL_ROL instance);
    partial void DeleteTBL_ROL(TBL_ROL instance);
    partial void InsertTBL_USUARIO(TBL_USUARIO instance);
    partial void UpdateTBL_USUARIO(TBL_USUARIO instance);
    partial void DeleteTBL_USUARIO(TBL_USUARIO instance);
    partial void InsertEmpleado_Cacuango(Empleado_Cacuango instance);
    partial void UpdateEmpleado_Cacuango(Empleado_Cacuango instance);
    partial void DeleteEmpleado_Cacuango(Empleado_Cacuango instance);
    #endregion
		
		public DCExamenDataContext() : 
				base(global::Modelo.Properties.Settings.Default.DBHELPDESK01ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DCExamenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCExamenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCExamenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCExamenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_DEPARTAMENTO> TBL_DEPARTAMENTO
		{
			get
			{
				return this.GetTable<TBL_DEPARTAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ESTADO> TBL_ESTADO
		{
			get
			{
				return this.GetTable<TBL_ESTADO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_INCIDENTE> TBL_INCIDENTE
		{
			get
			{
				return this.GetTable<TBL_INCIDENTE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_OBSERVACION> TBL_OBSERVACION
		{
			get
			{
				return this.GetTable<TBL_OBSERVACION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PERSONA> TBL_PERSONA
		{
			get
			{
				return this.GetTable<TBL_PERSONA>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PRIORIDAD> TBL_PRIORIDAD
		{
			get
			{
				return this.GetTable<TBL_PRIORIDAD>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ROL> TBL_ROL
		{
			get
			{
				return this.GetTable<TBL_ROL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this.GetTable<TBL_USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<Empleado_Cacuango> Empleado_Cacuango
		{
			get
			{
				return this.GetTable<Empleado_Cacuango>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.empleado")]
		public int empleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, cedula, estado);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DEPARTAMENTO")]
	public partial class TBL_DEPARTAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DEP_ID;
		
		private string _DEP_DESCRIPCION;
		
		private string _DEP_DIRECCION;
		
		private System.Nullable<char> _DEP_STATUS;
		
		private System.Nullable<System.DateTime> _DEP_ADD;
		
		private EntitySet<TBL_PERSONA> _TBL_PERSONA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDEP_IDChanging(int value);
    partial void OnDEP_IDChanged();
    partial void OnDEP_DESCRIPCIONChanging(string value);
    partial void OnDEP_DESCRIPCIONChanged();
    partial void OnDEP_DIRECCIONChanging(string value);
    partial void OnDEP_DIRECCIONChanged();
    partial void OnDEP_STATUSChanging(System.Nullable<char> value);
    partial void OnDEP_STATUSChanged();
    partial void OnDEP_ADDChanging(System.Nullable<System.DateTime> value);
    partial void OnDEP_ADDChanged();
    #endregion
		
		public TBL_DEPARTAMENTO()
		{
			this._TBL_PERSONA = new EntitySet<TBL_PERSONA>(new Action<TBL_PERSONA>(this.attach_TBL_PERSONA), new Action<TBL_PERSONA>(this.detach_TBL_PERSONA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DEP_ID
		{
			get
			{
				return this._DEP_ID;
			}
			set
			{
				if ((this._DEP_ID != value))
				{
					this.OnDEP_IDChanging(value);
					this.SendPropertyChanging();
					this._DEP_ID = value;
					this.SendPropertyChanged("DEP_ID");
					this.OnDEP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEP_DESCRIPCION", DbType="VarChar(50)")]
		public string DEP_DESCRIPCION
		{
			get
			{
				return this._DEP_DESCRIPCION;
			}
			set
			{
				if ((this._DEP_DESCRIPCION != value))
				{
					this.OnDEP_DESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DEP_DESCRIPCION = value;
					this.SendPropertyChanged("DEP_DESCRIPCION");
					this.OnDEP_DESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEP_DIRECCION", DbType="VarChar(200)")]
		public string DEP_DIRECCION
		{
			get
			{
				return this._DEP_DIRECCION;
			}
			set
			{
				if ((this._DEP_DIRECCION != value))
				{
					this.OnDEP_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DEP_DIRECCION = value;
					this.SendPropertyChanged("DEP_DIRECCION");
					this.OnDEP_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEP_STATUS", DbType="Char(1)")]
		public System.Nullable<char> DEP_STATUS
		{
			get
			{
				return this._DEP_STATUS;
			}
			set
			{
				if ((this._DEP_STATUS != value))
				{
					this.OnDEP_STATUSChanging(value);
					this.SendPropertyChanging();
					this._DEP_STATUS = value;
					this.SendPropertyChanged("DEP_STATUS");
					this.OnDEP_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEP_ADD", DbType="DateTime")]
		public System.Nullable<System.DateTime> DEP_ADD
		{
			get
			{
				return this._DEP_ADD;
			}
			set
			{
				if ((this._DEP_ADD != value))
				{
					this.OnDEP_ADDChanging(value);
					this.SendPropertyChanging();
					this._DEP_ADD = value;
					this.SendPropertyChanged("DEP_ADD");
					this.OnDEP_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DEPARTAMENTO_TBL_PERSONA", Storage="_TBL_PERSONA", ThisKey="DEP_ID", OtherKey="DEP_ID")]
		public EntitySet<TBL_PERSONA> TBL_PERSONA
		{
			get
			{
				return this._TBL_PERSONA;
			}
			set
			{
				this._TBL_PERSONA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PERSONA(TBL_PERSONA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DEPARTAMENTO = this;
		}
		
		private void detach_TBL_PERSONA(TBL_PERSONA entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DEPARTAMENTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ESTADO")]
	public partial class TBL_ESTADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EST_ID;
		
		private string _EST_DESCRIPCION;
		
		private System.Nullable<System.DateTime> _EST_ADD;
		
		private System.Nullable<char> _EST_STATUS;
		
		private EntitySet<TBL_INCIDENTE> _TBL_INCIDENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEST_IDChanging(int value);
    partial void OnEST_IDChanged();
    partial void OnEST_DESCRIPCIONChanging(string value);
    partial void OnEST_DESCRIPCIONChanged();
    partial void OnEST_ADDChanging(System.Nullable<System.DateTime> value);
    partial void OnEST_ADDChanged();
    partial void OnEST_STATUSChanging(System.Nullable<char> value);
    partial void OnEST_STATUSChanged();
    #endregion
		
		public TBL_ESTADO()
		{
			this._TBL_INCIDENTE = new EntitySet<TBL_INCIDENTE>(new Action<TBL_INCIDENTE>(this.attach_TBL_INCIDENTE), new Action<TBL_INCIDENTE>(this.detach_TBL_INCIDENTE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EST_ID
		{
			get
			{
				return this._EST_ID;
			}
			set
			{
				if ((this._EST_ID != value))
				{
					this.OnEST_IDChanging(value);
					this.SendPropertyChanging();
					this._EST_ID = value;
					this.SendPropertyChanged("EST_ID");
					this.OnEST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_DESCRIPCION", DbType="VarChar(50)")]
		public string EST_DESCRIPCION
		{
			get
			{
				return this._EST_DESCRIPCION;
			}
			set
			{
				if ((this._EST_DESCRIPCION != value))
				{
					this.OnEST_DESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._EST_DESCRIPCION = value;
					this.SendPropertyChanged("EST_DESCRIPCION");
					this.OnEST_DESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_ADD", DbType="DateTime")]
		public System.Nullable<System.DateTime> EST_ADD
		{
			get
			{
				return this._EST_ADD;
			}
			set
			{
				if ((this._EST_ADD != value))
				{
					this.OnEST_ADDChanging(value);
					this.SendPropertyChanging();
					this._EST_ADD = value;
					this.SendPropertyChanged("EST_ADD");
					this.OnEST_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_STATUS", DbType="Char(1)")]
		public System.Nullable<char> EST_STATUS
		{
			get
			{
				return this._EST_STATUS;
			}
			set
			{
				if ((this._EST_STATUS != value))
				{
					this.OnEST_STATUSChanging(value);
					this.SendPropertyChanging();
					this._EST_STATUS = value;
					this.SendPropertyChanged("EST_STATUS");
					this.OnEST_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ESTADO_TBL_INCIDENTE", Storage="_TBL_INCIDENTE", ThisKey="EST_ID", OtherKey="EST_ID")]
		public EntitySet<TBL_INCIDENTE> TBL_INCIDENTE
		{
			get
			{
				return this._TBL_INCIDENTE;
			}
			set
			{
				this._TBL_INCIDENTE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_INCIDENTE(TBL_INCIDENTE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ESTADO = this;
		}
		
		private void detach_TBL_INCIDENTE(TBL_INCIDENTE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ESTADO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_INCIDENTE")]
	public partial class TBL_INCIDENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _INC_ID;
		
		private System.Nullable<int> _PER_ID;
		
		private System.Nullable<int> _PRI_ID;
		
		private System.Nullable<int> _EST_ID;
		
		private System.Nullable<System.DateTime> _INC_FECHA;
		
		private System.Nullable<System.DateTime> _INC_VIGENCIA;
		
		private string _INC_NUMTICKET;
		
		private string _INC_COMENTARIO;
		
		private string _INC_TIPO;
		
		private System.Nullable<System.DateTime> _INC_ADD;
		
		private System.Nullable<char> _INC_STATUS;
		
		private EntitySet<TBL_OBSERVACION> _TBL_OBSERVACION;
		
		private EntityRef<TBL_ESTADO> _TBL_ESTADO;
		
		private EntityRef<TBL_PERSONA> _TBL_PERSONA;
		
		private EntityRef<TBL_PRIORIDAD> _TBL_PRIORIDAD;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnINC_IDChanging(int value);
    partial void OnINC_IDChanged();
    partial void OnPER_IDChanging(System.Nullable<int> value);
    partial void OnPER_IDChanged();
    partial void OnPRI_IDChanging(System.Nullable<int> value);
    partial void OnPRI_IDChanged();
    partial void OnEST_IDChanging(System.Nullable<int> value);
    partial void OnEST_IDChanged();
    partial void OnINC_FECHAChanging(System.Nullable<System.DateTime> value);
    partial void OnINC_FECHAChanged();
    partial void OnINC_VIGENCIAChanging(System.Nullable<System.DateTime> value);
    partial void OnINC_VIGENCIAChanged();
    partial void OnINC_NUMTICKETChanging(string value);
    partial void OnINC_NUMTICKETChanged();
    partial void OnINC_COMENTARIOChanging(string value);
    partial void OnINC_COMENTARIOChanged();
    partial void OnINC_TIPOChanging(string value);
    partial void OnINC_TIPOChanged();
    partial void OnINC_ADDChanging(System.Nullable<System.DateTime> value);
    partial void OnINC_ADDChanged();
    partial void OnINC_STATUSChanging(System.Nullable<char> value);
    partial void OnINC_STATUSChanged();
    #endregion
		
		public TBL_INCIDENTE()
		{
			this._TBL_OBSERVACION = new EntitySet<TBL_OBSERVACION>(new Action<TBL_OBSERVACION>(this.attach_TBL_OBSERVACION), new Action<TBL_OBSERVACION>(this.detach_TBL_OBSERVACION));
			this._TBL_ESTADO = default(EntityRef<TBL_ESTADO>);
			this._TBL_PERSONA = default(EntityRef<TBL_PERSONA>);
			this._TBL_PRIORIDAD = default(EntityRef<TBL_PRIORIDAD>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int INC_ID
		{
			get
			{
				return this._INC_ID;
			}
			set
			{
				if ((this._INC_ID != value))
				{
					this.OnINC_IDChanging(value);
					this.SendPropertyChanging();
					this._INC_ID = value;
					this.SendPropertyChanged("INC_ID");
					this.OnINC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_ID", DbType="Int")]
		public System.Nullable<int> PER_ID
		{
			get
			{
				return this._PER_ID;
			}
			set
			{
				if ((this._PER_ID != value))
				{
					if (this._TBL_PERSONA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPER_IDChanging(value);
					this.SendPropertyChanging();
					this._PER_ID = value;
					this.SendPropertyChanged("PER_ID");
					this.OnPER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRI_ID", DbType="Int")]
		public System.Nullable<int> PRI_ID
		{
			get
			{
				return this._PRI_ID;
			}
			set
			{
				if ((this._PRI_ID != value))
				{
					if (this._TBL_PRIORIDAD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPRI_IDChanging(value);
					this.SendPropertyChanging();
					this._PRI_ID = value;
					this.SendPropertyChanged("PRI_ID");
					this.OnPRI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_ID", DbType="Int")]
		public System.Nullable<int> EST_ID
		{
			get
			{
				return this._EST_ID;
			}
			set
			{
				if ((this._EST_ID != value))
				{
					if (this._TBL_ESTADO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEST_IDChanging(value);
					this.SendPropertyChanging();
					this._EST_ID = value;
					this.SendPropertyChanged("EST_ID");
					this.OnEST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> INC_FECHA
		{
			get
			{
				return this._INC_FECHA;
			}
			set
			{
				if ((this._INC_FECHA != value))
				{
					this.OnINC_FECHAChanging(value);
					this.SendPropertyChanging();
					this._INC_FECHA = value;
					this.SendPropertyChanged("INC_FECHA");
					this.OnINC_FECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_VIGENCIA", DbType="DateTime")]
		public System.Nullable<System.DateTime> INC_VIGENCIA
		{
			get
			{
				return this._INC_VIGENCIA;
			}
			set
			{
				if ((this._INC_VIGENCIA != value))
				{
					this.OnINC_VIGENCIAChanging(value);
					this.SendPropertyChanging();
					this._INC_VIGENCIA = value;
					this.SendPropertyChanged("INC_VIGENCIA");
					this.OnINC_VIGENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_NUMTICKET", DbType="VarChar(10)")]
		public string INC_NUMTICKET
		{
			get
			{
				return this._INC_NUMTICKET;
			}
			set
			{
				if ((this._INC_NUMTICKET != value))
				{
					this.OnINC_NUMTICKETChanging(value);
					this.SendPropertyChanging();
					this._INC_NUMTICKET = value;
					this.SendPropertyChanged("INC_NUMTICKET");
					this.OnINC_NUMTICKETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_COMENTARIO", DbType="VarChar(200)")]
		public string INC_COMENTARIO
		{
			get
			{
				return this._INC_COMENTARIO;
			}
			set
			{
				if ((this._INC_COMENTARIO != value))
				{
					this.OnINC_COMENTARIOChanging(value);
					this.SendPropertyChanging();
					this._INC_COMENTARIO = value;
					this.SendPropertyChanged("INC_COMENTARIO");
					this.OnINC_COMENTARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_TIPO", DbType="VarChar(100)")]
		public string INC_TIPO
		{
			get
			{
				return this._INC_TIPO;
			}
			set
			{
				if ((this._INC_TIPO != value))
				{
					this.OnINC_TIPOChanging(value);
					this.SendPropertyChanging();
					this._INC_TIPO = value;
					this.SendPropertyChanged("INC_TIPO");
					this.OnINC_TIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_ADD", DbType="DateTime")]
		public System.Nullable<System.DateTime> INC_ADD
		{
			get
			{
				return this._INC_ADD;
			}
			set
			{
				if ((this._INC_ADD != value))
				{
					this.OnINC_ADDChanging(value);
					this.SendPropertyChanging();
					this._INC_ADD = value;
					this.SendPropertyChanged("INC_ADD");
					this.OnINC_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_STATUS", DbType="Char(1)")]
		public System.Nullable<char> INC_STATUS
		{
			get
			{
				return this._INC_STATUS;
			}
			set
			{
				if ((this._INC_STATUS != value))
				{
					this.OnINC_STATUSChanging(value);
					this.SendPropertyChanging();
					this._INC_STATUS = value;
					this.SendPropertyChanged("INC_STATUS");
					this.OnINC_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_INCIDENTE_TBL_OBSERVACION", Storage="_TBL_OBSERVACION", ThisKey="INC_ID", OtherKey="INC_ID")]
		public EntitySet<TBL_OBSERVACION> TBL_OBSERVACION
		{
			get
			{
				return this._TBL_OBSERVACION;
			}
			set
			{
				this._TBL_OBSERVACION.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ESTADO_TBL_INCIDENTE", Storage="_TBL_ESTADO", ThisKey="EST_ID", OtherKey="EST_ID", IsForeignKey=true)]
		public TBL_ESTADO TBL_ESTADO
		{
			get
			{
				return this._TBL_ESTADO.Entity;
			}
			set
			{
				TBL_ESTADO previousValue = this._TBL_ESTADO.Entity;
				if (((previousValue != value) 
							|| (this._TBL_ESTADO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_ESTADO.Entity = null;
						previousValue.TBL_INCIDENTE.Remove(this);
					}
					this._TBL_ESTADO.Entity = value;
					if ((value != null))
					{
						value.TBL_INCIDENTE.Add(this);
						this._EST_ID = value.EST_ID;
					}
					else
					{
						this._EST_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_ESTADO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PERSONA_TBL_INCIDENTE", Storage="_TBL_PERSONA", ThisKey="PER_ID", OtherKey="PER_ID", IsForeignKey=true)]
		public TBL_PERSONA TBL_PERSONA
		{
			get
			{
				return this._TBL_PERSONA.Entity;
			}
			set
			{
				TBL_PERSONA previousValue = this._TBL_PERSONA.Entity;
				if (((previousValue != value) 
							|| (this._TBL_PERSONA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_PERSONA.Entity = null;
						previousValue.TBL_INCIDENTE.Remove(this);
					}
					this._TBL_PERSONA.Entity = value;
					if ((value != null))
					{
						value.TBL_INCIDENTE.Add(this);
						this._PER_ID = value.PER_ID;
					}
					else
					{
						this._PER_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_PERSONA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PRIORIDAD_TBL_INCIDENTE", Storage="_TBL_PRIORIDAD", ThisKey="PRI_ID", OtherKey="PRI_ID", IsForeignKey=true)]
		public TBL_PRIORIDAD TBL_PRIORIDAD
		{
			get
			{
				return this._TBL_PRIORIDAD.Entity;
			}
			set
			{
				TBL_PRIORIDAD previousValue = this._TBL_PRIORIDAD.Entity;
				if (((previousValue != value) 
							|| (this._TBL_PRIORIDAD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_PRIORIDAD.Entity = null;
						previousValue.TBL_INCIDENTE.Remove(this);
					}
					this._TBL_PRIORIDAD.Entity = value;
					if ((value != null))
					{
						value.TBL_INCIDENTE.Add(this);
						this._PRI_ID = value.PRI_ID;
					}
					else
					{
						this._PRI_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_PRIORIDAD");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_OBSERVACION(TBL_OBSERVACION entity)
		{
			this.SendPropertyChanging();
			entity.TBL_INCIDENTE = this;
		}
		
		private void detach_TBL_OBSERVACION(TBL_OBSERVACION entity)
		{
			this.SendPropertyChanging();
			entity.TBL_INCIDENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_OBSERVACION")]
	public partial class TBL_OBSERVACION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OBS_ID;
		
		private System.Nullable<int> _INC_ID;
		
		private System.Nullable<int> _PER_ID;
		
		private System.Nullable<System.DateTime> _OBS_FECHA;
		
		private string _OBS_COMETARIO;
		
		private System.Nullable<char> _OBS_STATUS;
		
		private System.Nullable<System.DateTime> _OBS_ADD;
		
		private EntityRef<TBL_INCIDENTE> _TBL_INCIDENTE;
		
		private EntityRef<TBL_PERSONA> _TBL_PERSONA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBS_IDChanging(int value);
    partial void OnOBS_IDChanged();
    partial void OnINC_IDChanging(System.Nullable<int> value);
    partial void OnINC_IDChanged();
    partial void OnPER_IDChanging(System.Nullable<int> value);
    partial void OnPER_IDChanged();
    partial void OnOBS_FECHAChanging(System.Nullable<System.DateTime> value);
    partial void OnOBS_FECHAChanged();
    partial void OnOBS_COMETARIOChanging(string value);
    partial void OnOBS_COMETARIOChanged();
    partial void OnOBS_STATUSChanging(System.Nullable<char> value);
    partial void OnOBS_STATUSChanged();
    partial void OnOBS_ADDChanging(System.Nullable<System.DateTime> value);
    partial void OnOBS_ADDChanged();
    #endregion
		
		public TBL_OBSERVACION()
		{
			this._TBL_INCIDENTE = default(EntityRef<TBL_INCIDENTE>);
			this._TBL_PERSONA = default(EntityRef<TBL_PERSONA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OBS_ID
		{
			get
			{
				return this._OBS_ID;
			}
			set
			{
				if ((this._OBS_ID != value))
				{
					this.OnOBS_IDChanging(value);
					this.SendPropertyChanging();
					this._OBS_ID = value;
					this.SendPropertyChanged("OBS_ID");
					this.OnOBS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INC_ID", DbType="Int")]
		public System.Nullable<int> INC_ID
		{
			get
			{
				return this._INC_ID;
			}
			set
			{
				if ((this._INC_ID != value))
				{
					if (this._TBL_INCIDENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnINC_IDChanging(value);
					this.SendPropertyChanging();
					this._INC_ID = value;
					this.SendPropertyChanged("INC_ID");
					this.OnINC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_ID", DbType="Int")]
		public System.Nullable<int> PER_ID
		{
			get
			{
				return this._PER_ID;
			}
			set
			{
				if ((this._PER_ID != value))
				{
					if (this._TBL_PERSONA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPER_IDChanging(value);
					this.SendPropertyChanging();
					this._PER_ID = value;
					this.SendPropertyChanged("PER_ID");
					this.OnPER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> OBS_FECHA
		{
			get
			{
				return this._OBS_FECHA;
			}
			set
			{
				if ((this._OBS_FECHA != value))
				{
					this.OnOBS_FECHAChanging(value);
					this.SendPropertyChanging();
					this._OBS_FECHA = value;
					this.SendPropertyChanged("OBS_FECHA");
					this.OnOBS_FECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS_COMETARIO", DbType="VarChar(500)")]
		public string OBS_COMETARIO
		{
			get
			{
				return this._OBS_COMETARIO;
			}
			set
			{
				if ((this._OBS_COMETARIO != value))
				{
					this.OnOBS_COMETARIOChanging(value);
					this.SendPropertyChanging();
					this._OBS_COMETARIO = value;
					this.SendPropertyChanged("OBS_COMETARIO");
					this.OnOBS_COMETARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS_STATUS", DbType="Char(1)")]
		public System.Nullable<char> OBS_STATUS
		{
			get
			{
				return this._OBS_STATUS;
			}
			set
			{
				if ((this._OBS_STATUS != value))
				{
					this.OnOBS_STATUSChanging(value);
					this.SendPropertyChanging();
					this._OBS_STATUS = value;
					this.SendPropertyChanged("OBS_STATUS");
					this.OnOBS_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS_ADD", DbType="DateTime")]
		public System.Nullable<System.DateTime> OBS_ADD
		{
			get
			{
				return this._OBS_ADD;
			}
			set
			{
				if ((this._OBS_ADD != value))
				{
					this.OnOBS_ADDChanging(value);
					this.SendPropertyChanging();
					this._OBS_ADD = value;
					this.SendPropertyChanged("OBS_ADD");
					this.OnOBS_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_INCIDENTE_TBL_OBSERVACION", Storage="_TBL_INCIDENTE", ThisKey="INC_ID", OtherKey="INC_ID", IsForeignKey=true)]
		public TBL_INCIDENTE TBL_INCIDENTE
		{
			get
			{
				return this._TBL_INCIDENTE.Entity;
			}
			set
			{
				TBL_INCIDENTE previousValue = this._TBL_INCIDENTE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_INCIDENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_INCIDENTE.Entity = null;
						previousValue.TBL_OBSERVACION.Remove(this);
					}
					this._TBL_INCIDENTE.Entity = value;
					if ((value != null))
					{
						value.TBL_OBSERVACION.Add(this);
						this._INC_ID = value.INC_ID;
					}
					else
					{
						this._INC_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_INCIDENTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PERSONA_TBL_OBSERVACION", Storage="_TBL_PERSONA", ThisKey="PER_ID", OtherKey="PER_ID", IsForeignKey=true)]
		public TBL_PERSONA TBL_PERSONA
		{
			get
			{
				return this._TBL_PERSONA.Entity;
			}
			set
			{
				TBL_PERSONA previousValue = this._TBL_PERSONA.Entity;
				if (((previousValue != value) 
							|| (this._TBL_PERSONA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_PERSONA.Entity = null;
						previousValue.TBL_OBSERVACION.Remove(this);
					}
					this._TBL_PERSONA.Entity = value;
					if ((value != null))
					{
						value.TBL_OBSERVACION.Add(this);
						this._PER_ID = value.PER_ID;
					}
					else
					{
						this._PER_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_PERSONA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PERSONA")]
	public partial class TBL_PERSONA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PER_ID;
		
		private System.Nullable<int> _DEP_ID;
		
		private string _PER_IDENTIFICACION;
		
		private string _PER_APELLIDOS;
		
		private string _PER_NOMBRE;
		
		private string _PER_DIRECCION;
		
		private string _PER_TELEFONO;
		
		private string _PER_EMAIL;
		
		private System.Nullable<char> _PER_STATUS;
		
		private System.Nullable<char> _PER_TIPOIDENTIFICACION;
		
		private System.Nullable<System.DateTime> _PER_ADD;
		
		private EntitySet<TBL_INCIDENTE> _TBL_INCIDENTE;
		
		private EntitySet<TBL_OBSERVACION> _TBL_OBSERVACION;
		
		private EntitySet<TBL_USUARIO> _TBL_USUARIO;
		
		private EntityRef<TBL_DEPARTAMENTO> _TBL_DEPARTAMENTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPER_IDChanging(int value);
    partial void OnPER_IDChanged();
    partial void OnDEP_IDChanging(System.Nullable<int> value);
    partial void OnDEP_IDChanged();
    partial void OnPER_IDENTIFICACIONChanging(string value);
    partial void OnPER_IDENTIFICACIONChanged();
    partial void OnPER_APELLIDOSChanging(string value);
    partial void OnPER_APELLIDOSChanged();
    partial void OnPER_NOMBREChanging(string value);
    partial void OnPER_NOMBREChanged();
    partial void OnPER_DIRECCIONChanging(string value);
    partial void OnPER_DIRECCIONChanged();
    partial void OnPER_TELEFONOChanging(string value);
    partial void OnPER_TELEFONOChanged();
    partial void OnPER_EMAILChanging(string value);
    partial void OnPER_EMAILChanged();
    partial void OnPER_STATUSChanging(System.Nullable<char> value);
    partial void OnPER_STATUSChanged();
    partial void OnPER_TIPOIDENTIFICACIONChanging(System.Nullable<char> value);
    partial void OnPER_TIPOIDENTIFICACIONChanged();
    partial void OnPER_ADDChanging(System.Nullable<System.DateTime> value);
    partial void OnPER_ADDChanged();
    #endregion
		
		public TBL_PERSONA()
		{
			this._TBL_INCIDENTE = new EntitySet<TBL_INCIDENTE>(new Action<TBL_INCIDENTE>(this.attach_TBL_INCIDENTE), new Action<TBL_INCIDENTE>(this.detach_TBL_INCIDENTE));
			this._TBL_OBSERVACION = new EntitySet<TBL_OBSERVACION>(new Action<TBL_OBSERVACION>(this.attach_TBL_OBSERVACION), new Action<TBL_OBSERVACION>(this.detach_TBL_OBSERVACION));
			this._TBL_USUARIO = new EntitySet<TBL_USUARIO>(new Action<TBL_USUARIO>(this.attach_TBL_USUARIO), new Action<TBL_USUARIO>(this.detach_TBL_USUARIO));
			this._TBL_DEPARTAMENTO = default(EntityRef<TBL_DEPARTAMENTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PER_ID
		{
			get
			{
				return this._PER_ID;
			}
			set
			{
				if ((this._PER_ID != value))
				{
					this.OnPER_IDChanging(value);
					this.SendPropertyChanging();
					this._PER_ID = value;
					this.SendPropertyChanged("PER_ID");
					this.OnPER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEP_ID", DbType="Int")]
		public System.Nullable<int> DEP_ID
		{
			get
			{
				return this._DEP_ID;
			}
			set
			{
				if ((this._DEP_ID != value))
				{
					if (this._TBL_DEPARTAMENTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDEP_IDChanging(value);
					this.SendPropertyChanging();
					this._DEP_ID = value;
					this.SendPropertyChanged("DEP_ID");
					this.OnDEP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_IDENTIFICACION", DbType="VarChar(15)")]
		public string PER_IDENTIFICACION
		{
			get
			{
				return this._PER_IDENTIFICACION;
			}
			set
			{
				if ((this._PER_IDENTIFICACION != value))
				{
					this.OnPER_IDENTIFICACIONChanging(value);
					this.SendPropertyChanging();
					this._PER_IDENTIFICACION = value;
					this.SendPropertyChanged("PER_IDENTIFICACION");
					this.OnPER_IDENTIFICACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_APELLIDOS", DbType="VarChar(50)")]
		public string PER_APELLIDOS
		{
			get
			{
				return this._PER_APELLIDOS;
			}
			set
			{
				if ((this._PER_APELLIDOS != value))
				{
					this.OnPER_APELLIDOSChanging(value);
					this.SendPropertyChanging();
					this._PER_APELLIDOS = value;
					this.SendPropertyChanged("PER_APELLIDOS");
					this.OnPER_APELLIDOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_NOMBRE", DbType="VarChar(50)")]
		public string PER_NOMBRE
		{
			get
			{
				return this._PER_NOMBRE;
			}
			set
			{
				if ((this._PER_NOMBRE != value))
				{
					this.OnPER_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._PER_NOMBRE = value;
					this.SendPropertyChanged("PER_NOMBRE");
					this.OnPER_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_DIRECCION", DbType="VarChar(100)")]
		public string PER_DIRECCION
		{
			get
			{
				return this._PER_DIRECCION;
			}
			set
			{
				if ((this._PER_DIRECCION != value))
				{
					this.OnPER_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._PER_DIRECCION = value;
					this.SendPropertyChanged("PER_DIRECCION");
					this.OnPER_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_TELEFONO", DbType="VarChar(10)")]
		public string PER_TELEFONO
		{
			get
			{
				return this._PER_TELEFONO;
			}
			set
			{
				if ((this._PER_TELEFONO != value))
				{
					this.OnPER_TELEFONOChanging(value);
					this.SendPropertyChanging();
					this._PER_TELEFONO = value;
					this.SendPropertyChanged("PER_TELEFONO");
					this.OnPER_TELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_EMAIL", DbType="VarChar(100)")]
		public string PER_EMAIL
		{
			get
			{
				return this._PER_EMAIL;
			}
			set
			{
				if ((this._PER_EMAIL != value))
				{
					this.OnPER_EMAILChanging(value);
					this.SendPropertyChanging();
					this._PER_EMAIL = value;
					this.SendPropertyChanged("PER_EMAIL");
					this.OnPER_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_STATUS", DbType="Char(1)")]
		public System.Nullable<char> PER_STATUS
		{
			get
			{
				return this._PER_STATUS;
			}
			set
			{
				if ((this._PER_STATUS != value))
				{
					this.OnPER_STATUSChanging(value);
					this.SendPropertyChanging();
					this._PER_STATUS = value;
					this.SendPropertyChanged("PER_STATUS");
					this.OnPER_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_TIPOIDENTIFICACION", DbType="Char(1)")]
		public System.Nullable<char> PER_TIPOIDENTIFICACION
		{
			get
			{
				return this._PER_TIPOIDENTIFICACION;
			}
			set
			{
				if ((this._PER_TIPOIDENTIFICACION != value))
				{
					this.OnPER_TIPOIDENTIFICACIONChanging(value);
					this.SendPropertyChanging();
					this._PER_TIPOIDENTIFICACION = value;
					this.SendPropertyChanged("PER_TIPOIDENTIFICACION");
					this.OnPER_TIPOIDENTIFICACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_ADD", DbType="DateTime")]
		public System.Nullable<System.DateTime> PER_ADD
		{
			get
			{
				return this._PER_ADD;
			}
			set
			{
				if ((this._PER_ADD != value))
				{
					this.OnPER_ADDChanging(value);
					this.SendPropertyChanging();
					this._PER_ADD = value;
					this.SendPropertyChanged("PER_ADD");
					this.OnPER_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PERSONA_TBL_INCIDENTE", Storage="_TBL_INCIDENTE", ThisKey="PER_ID", OtherKey="PER_ID")]
		public EntitySet<TBL_INCIDENTE> TBL_INCIDENTE
		{
			get
			{
				return this._TBL_INCIDENTE;
			}
			set
			{
				this._TBL_INCIDENTE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PERSONA_TBL_OBSERVACION", Storage="_TBL_OBSERVACION", ThisKey="PER_ID", OtherKey="PER_ID")]
		public EntitySet<TBL_OBSERVACION> TBL_OBSERVACION
		{
			get
			{
				return this._TBL_OBSERVACION;
			}
			set
			{
				this._TBL_OBSERVACION.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PERSONA_TBL_USUARIO", Storage="_TBL_USUARIO", ThisKey="PER_ID", OtherKey="PER_ID")]
		public EntitySet<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this._TBL_USUARIO;
			}
			set
			{
				this._TBL_USUARIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DEPARTAMENTO_TBL_PERSONA", Storage="_TBL_DEPARTAMENTO", ThisKey="DEP_ID", OtherKey="DEP_ID", IsForeignKey=true)]
		public TBL_DEPARTAMENTO TBL_DEPARTAMENTO
		{
			get
			{
				return this._TBL_DEPARTAMENTO.Entity;
			}
			set
			{
				TBL_DEPARTAMENTO previousValue = this._TBL_DEPARTAMENTO.Entity;
				if (((previousValue != value) 
							|| (this._TBL_DEPARTAMENTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_DEPARTAMENTO.Entity = null;
						previousValue.TBL_PERSONA.Remove(this);
					}
					this._TBL_DEPARTAMENTO.Entity = value;
					if ((value != null))
					{
						value.TBL_PERSONA.Add(this);
						this._DEP_ID = value.DEP_ID;
					}
					else
					{
						this._DEP_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_DEPARTAMENTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_INCIDENTE(TBL_INCIDENTE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PERSONA = this;
		}
		
		private void detach_TBL_INCIDENTE(TBL_INCIDENTE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PERSONA = null;
		}
		
		private void attach_TBL_OBSERVACION(TBL_OBSERVACION entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PERSONA = this;
		}
		
		private void detach_TBL_OBSERVACION(TBL_OBSERVACION entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PERSONA = null;
		}
		
		private void attach_TBL_USUARIO(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PERSONA = this;
		}
		
		private void detach_TBL_USUARIO(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PERSONA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PRIORIDAD")]
	public partial class TBL_PRIORIDAD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PRI_ID;
		
		private string _PRI_NOMBRE;
		
		private System.Nullable<char> _PRI_STATUS;
		
		private System.Nullable<System.DateTime> _PRI_ADD;
		
		private EntitySet<TBL_INCIDENTE> _TBL_INCIDENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPRI_IDChanging(int value);
    partial void OnPRI_IDChanged();
    partial void OnPRI_NOMBREChanging(string value);
    partial void OnPRI_NOMBREChanged();
    partial void OnPRI_STATUSChanging(System.Nullable<char> value);
    partial void OnPRI_STATUSChanged();
    partial void OnPRI_ADDChanging(System.Nullable<System.DateTime> value);
    partial void OnPRI_ADDChanged();
    #endregion
		
		public TBL_PRIORIDAD()
		{
			this._TBL_INCIDENTE = new EntitySet<TBL_INCIDENTE>(new Action<TBL_INCIDENTE>(this.attach_TBL_INCIDENTE), new Action<TBL_INCIDENTE>(this.detach_TBL_INCIDENTE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRI_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PRI_ID
		{
			get
			{
				return this._PRI_ID;
			}
			set
			{
				if ((this._PRI_ID != value))
				{
					this.OnPRI_IDChanging(value);
					this.SendPropertyChanging();
					this._PRI_ID = value;
					this.SendPropertyChanged("PRI_ID");
					this.OnPRI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRI_NOMBRE", DbType="VarChar(50)")]
		public string PRI_NOMBRE
		{
			get
			{
				return this._PRI_NOMBRE;
			}
			set
			{
				if ((this._PRI_NOMBRE != value))
				{
					this.OnPRI_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._PRI_NOMBRE = value;
					this.SendPropertyChanged("PRI_NOMBRE");
					this.OnPRI_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRI_STATUS", DbType="Char(1)")]
		public System.Nullable<char> PRI_STATUS
		{
			get
			{
				return this._PRI_STATUS;
			}
			set
			{
				if ((this._PRI_STATUS != value))
				{
					this.OnPRI_STATUSChanging(value);
					this.SendPropertyChanging();
					this._PRI_STATUS = value;
					this.SendPropertyChanged("PRI_STATUS");
					this.OnPRI_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRI_ADD", DbType="DateTime")]
		public System.Nullable<System.DateTime> PRI_ADD
		{
			get
			{
				return this._PRI_ADD;
			}
			set
			{
				if ((this._PRI_ADD != value))
				{
					this.OnPRI_ADDChanging(value);
					this.SendPropertyChanging();
					this._PRI_ADD = value;
					this.SendPropertyChanged("PRI_ADD");
					this.OnPRI_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PRIORIDAD_TBL_INCIDENTE", Storage="_TBL_INCIDENTE", ThisKey="PRI_ID", OtherKey="PRI_ID")]
		public EntitySet<TBL_INCIDENTE> TBL_INCIDENTE
		{
			get
			{
				return this._TBL_INCIDENTE;
			}
			set
			{
				this._TBL_INCIDENTE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_INCIDENTE(TBL_INCIDENTE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PRIORIDAD = this;
		}
		
		private void detach_TBL_INCIDENTE(TBL_INCIDENTE entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PRIORIDAD = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ROL")]
	public partial class TBL_ROL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ROL_ID;
		
		private string _ROL_DESCRIPCION;
		
		private System.Nullable<System.DateTime> _ROL_ADD;
		
		private System.Nullable<char> _ROL_STATUS;
		
		private EntitySet<TBL_USUARIO> _TBL_USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnROL_IDChanging(int value);
    partial void OnROL_IDChanged();
    partial void OnROL_DESCRIPCIONChanging(string value);
    partial void OnROL_DESCRIPCIONChanged();
    partial void OnROL_ADDChanging(System.Nullable<System.DateTime> value);
    partial void OnROL_ADDChanged();
    partial void OnROL_STATUSChanging(System.Nullable<char> value);
    partial void OnROL_STATUSChanged();
    #endregion
		
		public TBL_ROL()
		{
			this._TBL_USUARIO = new EntitySet<TBL_USUARIO>(new Action<TBL_USUARIO>(this.attach_TBL_USUARIO), new Action<TBL_USUARIO>(this.detach_TBL_USUARIO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ROL_ID
		{
			get
			{
				return this._ROL_ID;
			}
			set
			{
				if ((this._ROL_ID != value))
				{
					this.OnROL_IDChanging(value);
					this.SendPropertyChanging();
					this._ROL_ID = value;
					this.SendPropertyChanged("ROL_ID");
					this.OnROL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL_DESCRIPCION", DbType="VarChar(100)")]
		public string ROL_DESCRIPCION
		{
			get
			{
				return this._ROL_DESCRIPCION;
			}
			set
			{
				if ((this._ROL_DESCRIPCION != value))
				{
					this.OnROL_DESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._ROL_DESCRIPCION = value;
					this.SendPropertyChanged("ROL_DESCRIPCION");
					this.OnROL_DESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL_ADD", DbType="DateTime")]
		public System.Nullable<System.DateTime> ROL_ADD
		{
			get
			{
				return this._ROL_ADD;
			}
			set
			{
				if ((this._ROL_ADD != value))
				{
					this.OnROL_ADDChanging(value);
					this.SendPropertyChanging();
					this._ROL_ADD = value;
					this.SendPropertyChanged("ROL_ADD");
					this.OnROL_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL_STATUS", DbType="Char(1)")]
		public System.Nullable<char> ROL_STATUS
		{
			get
			{
				return this._ROL_STATUS;
			}
			set
			{
				if ((this._ROL_STATUS != value))
				{
					this.OnROL_STATUSChanging(value);
					this.SendPropertyChanging();
					this._ROL_STATUS = value;
					this.SendPropertyChanged("ROL_STATUS");
					this.OnROL_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ROL_TBL_USUARIO", Storage="_TBL_USUARIO", ThisKey="ROL_ID", OtherKey="ROL_ID")]
		public EntitySet<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this._TBL_USUARIO;
			}
			set
			{
				this._TBL_USUARIO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_USUARIO(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ROL = this;
		}
		
		private void detach_TBL_USUARIO(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_ROL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USUARIO")]
	public partial class TBL_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USU_ID;
		
		private System.Nullable<int> _PER_ID;
		
		private System.Nullable<int> _ROL_ID;
		
		private string _USU_LOGIN;
		
		private string _USU_PASSWORD;
		
		private string _USU_EMAIL;
		
		private System.Nullable<char> _USU_STATUS;
		
		private System.Nullable<System.DateTime> _USU_ADD;
		
		private EntityRef<TBL_PERSONA> _TBL_PERSONA;
		
		private EntityRef<TBL_ROL> _TBL_ROL;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSU_IDChanging(int value);
    partial void OnUSU_IDChanged();
    partial void OnPER_IDChanging(System.Nullable<int> value);
    partial void OnPER_IDChanged();
    partial void OnROL_IDChanging(System.Nullable<int> value);
    partial void OnROL_IDChanged();
    partial void OnUSU_LOGINChanging(string value);
    partial void OnUSU_LOGINChanged();
    partial void OnUSU_PASSWORDChanging(string value);
    partial void OnUSU_PASSWORDChanged();
    partial void OnUSU_EMAILChanging(string value);
    partial void OnUSU_EMAILChanged();
    partial void OnUSU_STATUSChanging(System.Nullable<char> value);
    partial void OnUSU_STATUSChanged();
    partial void OnUSU_ADDChanging(System.Nullable<System.DateTime> value);
    partial void OnUSU_ADDChanged();
    #endregion
		
		public TBL_USUARIO()
		{
			this._TBL_PERSONA = default(EntityRef<TBL_PERSONA>);
			this._TBL_ROL = default(EntityRef<TBL_ROL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int USU_ID
		{
			get
			{
				return this._USU_ID;
			}
			set
			{
				if ((this._USU_ID != value))
				{
					this.OnUSU_IDChanging(value);
					this.SendPropertyChanging();
					this._USU_ID = value;
					this.SendPropertyChanged("USU_ID");
					this.OnUSU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_ID", DbType="Int")]
		public System.Nullable<int> PER_ID
		{
			get
			{
				return this._PER_ID;
			}
			set
			{
				if ((this._PER_ID != value))
				{
					if (this._TBL_PERSONA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPER_IDChanging(value);
					this.SendPropertyChanging();
					this._PER_ID = value;
					this.SendPropertyChanged("PER_ID");
					this.OnPER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROL_ID", DbType="Int")]
		public System.Nullable<int> ROL_ID
		{
			get
			{
				return this._ROL_ID;
			}
			set
			{
				if ((this._ROL_ID != value))
				{
					if (this._TBL_ROL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnROL_IDChanging(value);
					this.SendPropertyChanging();
					this._ROL_ID = value;
					this.SendPropertyChanged("ROL_ID");
					this.OnROL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_LOGIN", DbType="VarChar(100)")]
		public string USU_LOGIN
		{
			get
			{
				return this._USU_LOGIN;
			}
			set
			{
				if ((this._USU_LOGIN != value))
				{
					this.OnUSU_LOGINChanging(value);
					this.SendPropertyChanging();
					this._USU_LOGIN = value;
					this.SendPropertyChanged("USU_LOGIN");
					this.OnUSU_LOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_PASSWORD", DbType="VarChar(100)")]
		public string USU_PASSWORD
		{
			get
			{
				return this._USU_PASSWORD;
			}
			set
			{
				if ((this._USU_PASSWORD != value))
				{
					this.OnUSU_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._USU_PASSWORD = value;
					this.SendPropertyChanged("USU_PASSWORD");
					this.OnUSU_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_EMAIL", DbType="VarChar(100)")]
		public string USU_EMAIL
		{
			get
			{
				return this._USU_EMAIL;
			}
			set
			{
				if ((this._USU_EMAIL != value))
				{
					this.OnUSU_EMAILChanging(value);
					this.SendPropertyChanging();
					this._USU_EMAIL = value;
					this.SendPropertyChanged("USU_EMAIL");
					this.OnUSU_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_STATUS", DbType="Char(1)")]
		public System.Nullable<char> USU_STATUS
		{
			get
			{
				return this._USU_STATUS;
			}
			set
			{
				if ((this._USU_STATUS != value))
				{
					this.OnUSU_STATUSChanging(value);
					this.SendPropertyChanging();
					this._USU_STATUS = value;
					this.SendPropertyChanged("USU_STATUS");
					this.OnUSU_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_ADD", DbType="DateTime")]
		public System.Nullable<System.DateTime> USU_ADD
		{
			get
			{
				return this._USU_ADD;
			}
			set
			{
				if ((this._USU_ADD != value))
				{
					this.OnUSU_ADDChanging(value);
					this.SendPropertyChanging();
					this._USU_ADD = value;
					this.SendPropertyChanged("USU_ADD");
					this.OnUSU_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PERSONA_TBL_USUARIO", Storage="_TBL_PERSONA", ThisKey="PER_ID", OtherKey="PER_ID", IsForeignKey=true)]
		public TBL_PERSONA TBL_PERSONA
		{
			get
			{
				return this._TBL_PERSONA.Entity;
			}
			set
			{
				TBL_PERSONA previousValue = this._TBL_PERSONA.Entity;
				if (((previousValue != value) 
							|| (this._TBL_PERSONA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_PERSONA.Entity = null;
						previousValue.TBL_USUARIO.Remove(this);
					}
					this._TBL_PERSONA.Entity = value;
					if ((value != null))
					{
						value.TBL_USUARIO.Add(this);
						this._PER_ID = value.PER_ID;
					}
					else
					{
						this._PER_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_PERSONA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_ROL_TBL_USUARIO", Storage="_TBL_ROL", ThisKey="ROL_ID", OtherKey="ROL_ID", IsForeignKey=true)]
		public TBL_ROL TBL_ROL
		{
			get
			{
				return this._TBL_ROL.Entity;
			}
			set
			{
				TBL_ROL previousValue = this._TBL_ROL.Entity;
				if (((previousValue != value) 
							|| (this._TBL_ROL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_ROL.Entity = null;
						previousValue.TBL_USUARIO.Remove(this);
					}
					this._TBL_ROL.Entity = value;
					if ((value != null))
					{
						value.TBL_USUARIO.Add(this);
						this._ROL_ID = value.ROL_ID;
					}
					else
					{
						this._ROL_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_ROL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado_Cacuango")]
	public partial class Empleado_Cacuango : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _apellidos;
		
		private string _cedula;
		
		private System.Nullable<char> _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OncedulaChanging(string value);
    partial void OncedulaChanged();
    partial void OnestadoChanging(System.Nullable<char> value);
    partial void OnestadoChanged();
    #endregion
		
		public Empleado_Cacuango()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(50)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(20)")]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1)")]
		public System.Nullable<char> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
